spring.application.name=cookie-login-api
spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.sql.init.mode=always