spring.application.name=cookie-login-api
spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.initialization.mode=always
userLegayDateTimeCode=false&serverTimezone=UTC